export const ACCOUNTS_REQUESTED = 'ACCOUNTS_REQUESTED';
export const ACCOUNTS_RECEIVED = 'ACCOUNTS_RECEIVED';
export const ACCOUNTS_ERROR = 'ACCOUNTS_ERROR';

export const BILLS_REQUESTED = 'BILLS_REQUESTED';
export const BILLS_RECEIVED = 'BILLS_RECEIVED';
export const BILLS_ERROR = 'BILLS_ERROR';

export const INCOMES_REQUESTED = 'INCOMES_REQUESTED';
export const INCOMES_RECEIVED = 'INCOMES_RECEIVED';
export const INCOMES_ERROR = 'INCOMES_ERROR';

export const AUTH_REQUESTED = 'AUTH_REQUESTED';
export const AUTH_RECEIVED = 'AUTH_RECEIVED';
export const AUTH_ERROR = 'AUTH_ERROR';