export const ACCOUNTS_REQUESTED = 'ACCOUNTS_REQUESTED';
export const ACCOUNTS_RECEIVED = 'ACCOUNTS_RECEIVED';
export const ACCOUNTS_ERROR = 'ACCOUNTS_ERROR';

export const DEBTS_REQUESTED = 'DEBTS_REQUESTED';
export const DEBTS_RECEIVED = 'DEBTS_RECEIVED';
export const DEBTS_ERROR = 'DEBTS_ERROR';

export const INCOMES_REQUESTED = 'INCOMES_REQUESTED';
export const INCOMES_RECEIVED = 'INCOMES_RECEIVED';
export const INCOMES_ERROR = 'INCOMES_ERROR';

export const AUTH_REQUESTED = 'AUTH_REQUESTED';
export const AUTH_RECEIVED = 'AUTH_RECEIVED';
export const AUTH_ERROR = 'AUTH_ERROR';

export const ACTIONS_REQUESTED = 'ACTIONS_REQUESTED';
export const ACTIONS_RECEIVED = 'ACTIONS_RECEIVED';
export const ACTIONS_ERROR = 'ACTIONS_ERROR';